/*
Coded by Jingfelix
Time:20210112
*/
// level 1
#include <stdio.h>
int main(void)
{
    int num;
    num = getchar();

    if (num >= 0 && num <= 9)
        printf("%d", num);
    else if (num >= 'a' && num <= 'f')
        printf("%d", num - 'a' + 10);
    else if (num >= 'A' && num <= 'F')
        printf("%d", num - 'A' + 10);
    else
        printf("%c", num);
    return 0;
}
// level 2
#include <stdio.h>
int main(void)
{
    unsigned short num, num_1, num_2;
    scanf("%u", &num);
    num_1 = num >> 12;
    num_2 = num << 12;
    num = num >> 4;
    num = num << 8;
    num = num >> 4;
    printf("%u", num + num_1 + num_2);
    return 0;
}
// level 3
#include <stdio.h>
int main(void)
{
    int a, b, c;
    scanf("%d %d %d", &a, &b, &c);
    if ((a <= b && a > c) || (a < c && a >= b))
        printf("A %d", a);
    else if ((b > a && b < c) || (b > c && b < a))
        printf("B %d", b);
    else if ((c > a && c < b) || (c > b && c < a))
        printf("C %d", c);

    return 0;
}
// level 4
#include <stdio.h>
int main()
{
    int year, month, day, date;             //声明年月日，输出的日期；
    scanf("%d %d %d", &year, &month, &day); //获取年月日
    //判断是否为闰年
    if ((((year % 4) == 0) && ((year % 100) != 0)) || (year % 400) == 0)
    {
        year = 1;
    }
    else
        year = 0;
    //日期分月计算
    switch (month)
    {
    case 1:
        date = day;
        break;
    case 2:
        date = 31 + day + year;
        break;
    case 3:
        date = 59 + day + year;
        break;
    case 4:
        date = 90 + day + year;
        break;
    case 5:
        date = 120 + day + year;
        break;
    case 6:
        date = 151 + day + year;
        break;
    case 7:
        date = 181 + day + year;
        break;
    case 8:
        date = 212 + day + year;
        break;
    case 9:
        date = 243 + day + year;
        break;
    case 10:
        date = 273 + day + year;
        break;
    case 11:
        date = 304 + day + year;
        break;
    case 12:
        date = 334 + day + year;
        break;
    }
    printf("%d", date); //输出数据
    return 0;
}
// level 5
#include <stdio.h>

int main(void)
{
    double num_1 = 0.0, num_2 = 0.0, sum = 0.0;
    char sign = 0;
    scanf("%lf %lf %c", &num_1, &num_2, &sign);
    //sign = '-' ;
    if (sign == '+')
    {
        sum = num_1 + num_2;
    }
    else if (sign == '-')
    {
        sum = num_1 - num_2;
    }
    else if (sign == '*')
    {
        sum = num_1 * num_2;
    }
    else if (sign == '/')
    {
        if (num_2 == 0)
        {
            sign = 'X';
        }
        else
        {
            sum = num_1 / num_2;
        }
    }
    else
        sign = 'X';
    if (sign != 'X')
        printf("%.6f", sum);
    else
        printf("Error");

    return 0;
}
// level 6
#include <stdio.h>
long fabonacci(int n);
int main(void)
{
    int n = 0;
    scanf("%d", &n);
    for (int i = 1; i <= n; i++)
    {
        printf("%6d", fabonacci(i));
        if ((i % 8) == 0)
            printf("\n");
    }
    return 0;
}
long fabonacci(int n)
{
    if (n == 1 || n == 2)
        return 1;
    else
        return fabonacci(n - 1) + fabonacci(n - 2);
}
// level 7 Output:3.141573
#include <stdio.h>
#include <math.h>
int main(void)
{
    double num = 0;
    for (float i = 1; (1.0 / (2 * i - 1)) > 0.00001; i++)
    {
        num += pow(-1,i) * (1.0 / (2 * i - 1)) * -1;
    }
    printf("%lf", 4 * num);    
}
// level 8
#include<stdio.h>

int gcd(int a, int b);
int gcb(int a, int b);
int main(void){
	int a, b;
	scanf("%d %d",&a,&b);
	// Èôa<bÔò½»»» 
	if (a<b){
		int c;
		c = b;
		b = a;
		a = c;
	}
	int GCD;
	GCD = gcd(a,b);
	printf("%d %d",GCD,gcb(a, b));
	return 0;
}
int gcd(int a, int b){
	if ((a%b)==0)
		return b;
	return(gcd(b, a%b));
}
int gcb(int a, int b){
	return (a*b/gcd(a,b));
}
// level 9
#include<stdio.h>
int count=0,end=0,num;
void hailstone(int n){
	printf("%4d",n);
	if (n%2 ==0)
		n /= 2;
	else if ((n%2==1)&&(n!=1))
		n = 3 * n + 1;
	else{
		end = 1;
	}
	num = n;
	count++;
}
int main(void){
	scanf("%d",&num);
	printf("Hailstone generated by %d:\n",num);
	while(!end){
		hailstone(num);
		if (((count%6)==0)&&(!end))
			printf("\n");	
	}
	printf("\nNumber of hailstone generated:%d",count);
	return 0;
}
// level 10
#include<stdio.h>
#include<math.h>
int digit(long n,int k){
	if ((n<pow(10,k-1)))
		return -1;
	else{
		n = n/pow(10,k-1);
		return (n%10);
	}	
}
int main(void){
	long n;
	int k;
	scanf("%d %d",&n,&k);
	printf("%d",digit(n,k));
	return 0;
}
// level 11
#include<stdio.h>
void function(void){
	char ch;
	ch = getchar();
	if (ch!=EOF) {
		function();
		printf("%c",ch);
    }
}
int main(void){
	function();
    putchar('\n');
	return 0;
}
// level 12
#define swap(a,b) {a=a-b;b=b+a;a=b-a;}
#include<stdio.h>
int main(void){
	int a,b;
	scanf("%d %d",&a,&b);
	swap(a,b)
	printf("%d %d",a,b);
	return 0;
}
// level 13
#include<stdio.h>
void arrange(int lst[],int n);
int main(void){
	int n=0;
	scanf("%d",&n);
	int lst[n];
	int num=0;
	for(int count=0;count<n;count++){
		if (count-(n-1))
			scanf("%d ",&num);
		else 
			scanf("%d",&num);
		lst[count] = num;
	} 
	arrange(lst,n);
	return 0;
}
void arrange(int lst[],int n){
	int count=0, count2=1;
	for (count=0; count<n; count++){
		for (count2=count+1; count2<n; count2++){
			if (lst[count]>lst[count2]){
				lst[count] = lst[count2]-lst[count];
				lst[count2]= lst[count2]-lst[count];
				lst[count] = lst[count] +lst[count2];
			}
		}
		printf("%d",lst[count]);
		if (count-n+1)
			printf(" ");	
	} 
}
// level 14
#include<stdio.h>
int main(void) {
	int num, change, count=0;
	scanf("%d %d", &num, &change);
	int numlist[num], changelist[change];

	for (int i=0; i<num; i++) {
		if ((num-i-1))
			scanf("%d ",&numlist[i]);
		else
			scanf("%d",&numlist[i]);
	}
	for (int i=0; i<num; i++) {
		if (i < change) {
			changelist[i] = numlist[count];
			count++;
		} else {
			numlist[i-change] = numlist[i];
		}
	}
	count=0;
	for (int i=num-change; i<num; i++) {
		numlist[i] = changelist[count];
		count++;
	}
	for (int i=0; i<num; i++) {
		printf("%d ",numlist[i]);
	}

	return 0;
}
// level 15
#include<stdio.h>
#include<string.h>
int main(void) {
	char ch[50];
	int num = 0, cha = 0, other = 0;
	gets(ch);
	for (int i = 0; i < strlen(ch); i++)
	{
		if (ch[i]>='0'&&ch[i]<='9')
		{
			num++;
		} else if ((ch[i]>='a' && ch[i]<='z')||(ch[i]>='A' && ch[i]<='Z')) {
			cha++;
		} else {
			other++;
		}
	}
	printf("%d %d %d", num, cha, other);
	return 0;
}
// level 16
#include<stdio.h>
void strncpy(char [], char [], int n);
int main(void)
{
	char s[50], t[50];
	int  n;
	scanf("%s %s %d", &s, &t, &n);
	strncpy(s, t, n);
	return 0 ;
}
void strncpy(char s[], char t[], int n) {
	for (int i = 0; i < n; i++) {
		s[i] = t[i];
	}
	printf("%s",s);	
}
// level 17
#include<stdio.h>
int main(void) {
	int result;
	char ch = 0;
	int num;
	scanf("%d", &num);
	num = 0;
	getchar();
	while (1) {
		ch = getchar();
		if (ch == EOF) {
			printf("%d", result);
			break;
		} else if (ch == ' ') {
			printf("%d ", result);
			result = 0;
		} else if (ch == '0') {
			ch=getchar();
			if (ch == 'x') {
			} else {
				result *= 16;
			}
		} else {
			if (ch >= '0' && ch <= '9') {
				num -= '0';
			} else if (ch >= 'a' && ch <= 'f') {
				num -= 'a';
			} else if (ch >= 'A' && ch <= 'F') {
				num -= 'A';
			}
			result = result*16 + num;
		}
	}
	return 0;
}
// level 18
#include<stdio.h>
int main(void) {
	int list[5];
	for (int i = 0; i < 5; i++) {
		scanf("%d", &list[i]);
	}
	int *ptr=&list[0];
	int temp;
	for (int i = 0; i < 4; i++) {
		ptr = &list[0];
		for (int j = 0; j < 4-i; j++)	{
			if (*(ptr) > *(ptr + 1)) {
				temp = *(ptr);
				*(ptr) = *(ptr + 1);
				*(ptr + 1) = temp;
			}
			ptr++;
		}
	}
	for (int i = 0; i < 5; i++)  {
		printf("%d ",list[i]);
	}
	return 0;
}
// level 19
#include<stdio.h>
int main(void) {
	int num;
	scanf("%d",&num);
	int list[num], list2[num];
	for (int i = 0; i < num; i++) {
		scanf("%d", &list[i]);
	}
	int temp;
	for (int i = 0; i != num/2; i++) {
		temp = list[i];
		list[i] = list[num-i-1];
		list[num-i-1] =  temp;
	}
	for (int i = 0; i < num; i++) {
		printf("%d ", list[i]);
	}
	return 0;
}
// level 20
#include <stdio.h>
struct date {
	int year;
	int month;
	int day;
};
int	main(void) {
	struct date date_1;
	scanf("%d %d %d", &(date_1.year), &(date_1.month), &(date_1.day));
	int date;
	int month_list[12] = {1,3,5,7,8,10,12,2,4,6,9,11};
	int leap = ((((date_1.year%4) == 0) && ((date_1.year%100) != 0)) || (date_1.year%400) == 0) ? 1 : 0;
	for (int i = 0; i < 12; i++)
	{
		if ((i < 7 && date_1.month == month_list[i] && date_1.day > 31) || (i >= 7 && date_1.month == month_list[i] && date_1.day > 30))
		{
			printf("error");
			return 0;
		}
	}
	if (date_1.month == 2 && date_1.day > 28 + leap)
	{
		printf("error");
		return 0;
	}
	switch(date_1.month) {
		case 1 :
			date = date_1.day ;
			break;
		case 2 :
			date = 31 + date_1.day ;
			break;
		case 3 :
			date = 59 + date_1.day + leap	;
			break;
		case 4 :
			date = 90 + date_1.day + leap ;
			break;
		case 5 :
			date = 120 + date_1.day + leap ;
			break;
		case 6 :
			date = 151 + date_1.day + leap ;
			break;
		case 7 :
			date = 181 + date_1.day + leap ;
			break;
		case 8 :
			date = 212 + date_1.day + leap ;
			break;
		case 9 :
			date = 243 + date_1.day + leap ;
			break;
		case 10 :
			date = 273 + date_1.day + leap ;
			break;
		case 11 :
			date = 304 + date_1.day + leap ;
			break;
		case 12 :
			date = 334 + date_1.day + leap ;
			break;
	}
	printf("%d", date);
	return 0;
}
// level 21
#include<stdio.h>
#include<string.h>
struct student
{
	int num;
	char name[12];
	double score;
};
int main(void) {
	struct student student_1 = {
		1, "BonBon", 100,
	}, *p_student_1 = &student_1;
	double score = student_1.score;
	printf("num = %d, name = %s, score = %1f\n", student_1.num, student_1.name, student_1.score);
	printf("num = %d, name = %s, score = %1f\n", p_student_1->num, p_student_1->name, p_student_1->score);
	return 0;
}
// level 22
#include<stdio.h>
#include<string.h>
struct web
{
	char abbr[20];
	char full[30];
	char url[50];
};
struct web hust =
{
	"华科大", "华中科技大学", "http://www.hust.edu.cn/"
}, *p_hust = &hust;
struct web baidu =
{
	"百度", "百度搜索网站", "http://www.baidu.com/index.php?tn=site888_pg"
}, *p_baidu = &baidu;

int main(void) {
	char name[20];
	scanf("%s", &name);
	if (!strcmp(name, hust.abbr))
		printf("%s", hust.url);
	else if (!strcmp(name, baidu.abbr))
		printf("%s", baidu.url);
	return 0;
}
// level 23
#include<stdio.h>
#include<stdlib.h>
struct T {
	int a[3], *pa;
	char b[20],*pb;
} s = {{-1,0,1},s.a,"bcdef",s.b},*ps=&s;
int main(void) {
	/*
	(1)++*s.a = 0
	(2)*s.a+2 = 1
	(3)*(s.a+2) = 1
	(4)ps->pa[1]++ = 0
	(5)++*++ps->pa = 1
	(6)*(s.b+2) = 'b'
	(7)*(++s.pb)+2 = 'e'
	(8)(++s.pb)[3] = 'f'
	(9)pa->pb[2]++ = ???
	(10)*(++ps->pb)++ = 'c'
	*/
	system("pause");
	return 0;
}
// level 24 25 28
// 没写
// level 26
#include<stdio.h>
int main()
{
    /*
    #define是编译预处理操作。在编译时编译器会将define的语句进行宏展开
    typedef是定义了新类型，编译后，每次调用时才生效
    */
    return 0;
}
// level 27
#include<stdio.h>
#include<string.h>
int isreturn(char *char_list, int list_lenth)
{	 
	if (list_lenth == 2 || (list_lenth == 1 || isreturn(char_list + 1, (list_lenth - 2))))
	{
		if (*char_list == (*(char_list + list_lenth - 1)))
		{
			return 1;
		} else {
			return 0;
		}
	} else {
		return 0;
	}
}
int main(void) {
	char inputstring[30];
	gets(inputstring);
	printf("%d", isreturn(inputstring, strlen(inputstring)));
	return 0;
}